spring:
  application:
    name: service-zuul-server
  sleuth:
    sampler:
      probability: 1.0

server:
  port: 8090

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  routes:
    products:
      service-id: service-products
      path: /api/products/**
    items:
      service-id: service-items
      path: /api/items/**
    users:
      service-id: service-users
      path: /api/users/**
    security:
      service-id: service-oauth
      path: /api/security/**
      sensitive-headers: Cookie,Set-Cookie

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 10000