spring:
  application:
    name: service-gateway-server
  cloud:
    gateway:
      routes:
        - id: service-products
          uri: lb://service-products
          predicates:
            - Path=/api/products/**
          filters:
            - StripPrefix=2
        - id: service-items
          uri: lb://service-items
          predicates:
            - Path=/api/items/**
          filters:
            - StripPrefix=2

server:
  port: 8090

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka