spring:
  application:
    name: service-gateway-server
  cloud:
    gateway:
      routes:
        - id: service-products
          uri: lb://service-products
          predicates:
            - Path=/api/products/**
          filters:
            - StripPrefix=2
            - ExampleCookie=Hi my message is customized, user, YanpieerRomero
        - id: service-items
          uri: lb://service-items
          predicates:
            - Path=/api/items/**
          filters:
            - StripPrefix=2
            - AddRequestHeader=token-request, 123456
            - AddResponseHeader=token-response, 12345678
            - SetResponseHeader=Content-Type, text/plain
            - AddRequestParameter=name, yanpieer

server:
  port: 8090

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka