spring:
  application:
    name: service-items
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411/

server:
  port: 8002

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

#hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 20000
#ribbon.ConnectTimeout: 3000
#ribbon.ReadTimeout: 10000